name: Build and test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: ocaml-variants.4.12.1+options,ocaml-option-flambda
          dune-cache: true

      - name: Install dependencies
        run: |
          opam install . --deps-only --with-test

      - name: Build
        run: opam exec dune build

      - name: Check formatting
        run: opam exec dune build @fmt

      - name: Run tests
        run: opam exec dune runtest
